swagger: 2.0
openapi: 3.1.0
info:
  title: Reminder - API - OpenAPI Docs 
  description: |-
    Documentação da API para a aplicação App Reminder.  

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: http://localhost:3000/api-docs
tags:
  - name: Notes
    description: Notas e Lembretes.
    externalDocs:
      description: Saiba mais em 
      url: http://
  - name: User
    description: Usuários.
    externalDocs:
      description: Saiba mais em 
      url: http://

paths:
  /users/criar:
    post:
      tags:
        - User
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuário criado com sucesso
  /users/login:
    post:
      tags:
        - User
      summary: Faz login com um usuário existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                senha:
                  type: string
      responses:
        '200':
          description: Login bem-sucedido
components:
  schemas:
    User:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
        cargo:
          type: string
        setor:
          type: string
        permissao:
          type: integer
