openapi: 3.1.0

info:
  title: Remind - API 
  description: |-
    Documentação da API para a aplicação App Remind.  

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: http://localhost:3000/api-docs

security:
  - api_key: []

tags:
  - name: User
    description: Operações relacionadas aos usuários.

paths:
  /users/criar:
    post:
      tags:
        - User
      summary: Cria um novo usuário
      description: Cria um novo usuário com os dados fornecidos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOutput'
        '400':
          description: Erro ao criar usuário.
      security:
        - api_key: []

  /users/login:
    post:
      tags:
        - User
      summary: Faz login com um usuário existente
      description: Faz login com as credenciais de um usuário existente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: Login bem-sucedido. Retorna informações do usuário e token de acesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginOutput'
        '400':
          description: Credenciais inválidas. 

components:
  schemas:
    UserInput:
      type: object
      properties:
        nome:
          type: string
          example: João Silva
        email:
          type: string
          format: email
          example: joao@example.com
        senha:
          type: string
          example: SenhaSegura123
        cargo:
          type: string
          example: Gerente de Vendas
        setor:
          type: string
          example: Vendas
        permissao:
          type: integer
          example: 1
      required:
        - nome
        - email
        - senha
        - cargo
        - setor
        - permissao

    UserOutput:
      type: object
      properties:
        _id:
          type: string
          example: 1234567890abcdef
        nome:
          type: string
          example: João Silva
        email:
          type: string
          format: email
          example: joao@example.com
        cargo:
          type: string
          example: Gerente de Vendas
        setor:
          type: string
          example: Vendas
        permissao:
          type: integer
          example: 1

    LoginInput:
      type: object
      properties:
        email:
          type: string
          format: email
          example: joao@example.com
        senha:
          type: string
          example: SenhaSegura123
      required:
        - email
        - senha

    LoginOutput:
      type: object
      properties:
        _id:
          type: string
          example: 1234567890abcdef
        nome:
          type: string
          example: João Silva
        email:
          type: string
          format: email
          example: joao@example.com
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
